### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by michelgokan** [flixpar/AlphaTSP#1]
Hi,

Just wanted to check whether this project is complete or not? It seems the code is incomplete and impossible to run (or is it?).

**Comment by flixpar** [comment]
All of the code is working and possible to run. Is there something specific that you are having trouble with?

**Comment by michelgokan** [comment]
@flixpar When I run the code using `python3 main.py --experiment selfplay` , the first error I'm getting is on the Line 75 in logger.py "TabError: inconsistent use of tabs and spaces in indentation"

But that was okay, I fixed that by replacing spaces with tabs. 

Then the next error was on line 73 in experiments/selfplay.py : `FileNotFoundError: [Errno 2] No such file or directory: 'saves/loss_parallel.png'`. This was also okay, as I created the "saves" directory and it fixed the error (it should create the directory if it's not exists though). 

Then the next error was in solvers/policy_networks.py in line 72/73: `AttributeError: 'dict' object has no attribute 'x'` I checked the file and found out that changing `=graph.x, graph.edge_index,gaph.y` to `=graph['x'], graph['edge_index'], graph['y']` can fix the error. 

But then the next error comes up: line 84 , there is no graph.num_nodes .... I tried replacing it with x.size(0) with a great suspicion. Error fixed. 

Then I got another error: "RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_bmm". I reviewed the code and saw that you sometimes used the device and sometimes you didn't, so I tried to add device everywhere....error fixed. But again, I got another error ..... as so on...

That's why I asked you whether this project is still under the test or not. Maybe I'm doing something wrong, but I'm not sure about it...Any thoughts?

**Comment by flixpar** [comment]
It seems that when I implemented supervised learning it broke the self-play code. I have reverted master to the point where self-play should work and branched the new code to the supervised branch. At some point I will try to update the self-play code to be compatible, but for now just use the new master branch.

**Comment by michelgokan** [comment]
@flixpar Thanks. I can't see any changes in the master that solve aforementioned issues. Have you pushed your changes?

**Comment by flixpar** [comment]
The issues you mentioned were caused by changes made when I added supervised learning. To fix the self-play code I didn't need to make any changes, just revert the code to the version before supervised learning was added. At some point I will update the self-play code to make it compatible and improve the multiprocessing but that will take some time. The version of the code in master will run now, but the multiprocessing code for self-play is a bit of a mess and may have minor bugs.

**Comment by michelgokan** [comment]
@flixpar It seems you made the changes locally and didn't push them to the origin. So nobody can see it.

**Comment by flixpar** [comment]
No, github shows master is at commit 50e38d0 rather than d441d86 as it was before.

**Comment by michelgokan** [comment]
@flixpar I cloned the repo again and it seems everything works fine. Thanks for the response.

**Comment by michelgokan** [comment]
It's under the test for a day now. I will keep it running during the weekend to see if it'll come up with the results or not...It's not printing any progress just says "Testing..."
